### PR TITLE
docs(readme): add twitter account and update github ID

### PR DESCRIPTION
**Pull request by DjangoPeng**
Update my github ID and add twitter account in contacts session.

@steven004 Would u like to add your twitter account?

I'll close issue #1 and #2 after merging this PR.

/cc @terichadbourne

### CODE REVIEW

**Comment by steven004** [comment]
Thanks for the update, Jingtian.
I am fine with the current change, and I will update my twitter info later.

@terichadbourne , I think currently I do not have the editing privileges of protoschool due to the two-factor authentication issue I had a few days ago. Now, I fixed it, would you
please re-add me in. thanks.

**Comment by DjangoPeng** [comment]
If no problem, I'd like to merge the PR. 

WDYT? @steven004

**Comment by steven004** [comment]
No problem, please go ahead for the merge.  Thanks.

**Comment by terichadbourne** [comment]
@steven004 I believe I've just added you back as an admin on this repo and as part of the `shanghai` and `chapter-organizers` teams. Let me know if you find I missed a permission setting somewhere. Thanks!

**Comment by steven004** [comment]
Thanks, Teri.

I received both invitation and accepted already. I am not sure if I need
the writing permission for the repo:
ProtoSchool <https://github.com/ProtoSchool>/protoschool.github.io
<https://github.com/ProtoSchool/protoschool.github.io>
If yes, please add me in, or just ignore this.

**Pull request merged**
